import '../scripts/asideFeedback'
import '../scripts/asideCallback'
import '../scripts/closeBurger'
import '../scripts/openBurger'
import '../scripts/readMoreBtn'
import '../scripts/serviceListClicks'
import '../scripts/showBrandsBtn'
import '../scripts/showRepairBtn'
import '../scripts/swiper'
import '../scripts/burgerListClicks'
import '../scripts/button-send'

import '../scss/style.scss'
